#!/usr/bin/env ruby

require 'td'

def list_all_commands
  command_output = `td help:all`
  commands = []
  command_output.split("\n").each { |cmd|
    if m = /^  ([^ ]+)/.match(cmd)
      commands << m[1] if not /^(status|bulk_import|apikey)/.match(m[1])
    end
  }
  commands
end

def format_cmd_detail(cmd_str)
  cmd_lines = []
  cmd_str.split("\n").each { |line|
    if /^\w+:/.match(line)
      cmd_lines << "#### " + line
      cmd_lines << "\n"
    elsif
      cmd_lines << ("  "+line)
    end
  }
  cmd_lines.join("\n")
end

out_file = File.new(File.dirname(__FILE__) + '/../docs/td-cli.txt', 'w')

intro = <<intro
<!--
This page is auto generated by generate_td_command_docs.rb
-->
# td command line tool reference

This page documents most of `td` subcommands.

intro

out_file.write(intro)

list_all_commands.each { |cmd|
  cmd_detail = format_cmd_detail(`td help #{cmd}`)

  desc = <<cmd

## td #{cmd}

#{cmd_detail}

cmd
  out_file.write(desc)
}
